// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(agentvecFFI)
import agentvecFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_agentvec_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_agentvec_mobile_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol AgentVecProtocol : AnyObject {
    
    func collection(name: String, dimensions: UInt32, metric: Metric) throws  -> Collection
    
    func collections() throws  -> [String]
    
    func dropCollection(name: String) throws 
    
    func getCollection(name: String) throws  -> Collection
    
    func recoveryStats()  -> RecoveryStats
    
    func sync() throws 
    
}

open class AgentVec:
    AgentVecProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_agentvec_mobile_fn_clone_agentvec(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_agentvec_mobile_fn_free_agentvec(pointer, $0) }
    }

    
public static func `open`(path: String)throws  -> AgentVec {
    return try  FfiConverterTypeAgentVec.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_constructor_agentvec_open(
        FfiConverterString.lower(path),$0
    )
})
}
    

    
open func collection(name: String, dimensions: UInt32, metric: Metric)throws  -> Collection {
    return try  FfiConverterTypeCollection.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_agentvec_collection(self.uniffiClonePointer(),
        FfiConverterString.lower(name),
        FfiConverterUInt32.lower(dimensions),
        FfiConverterTypeMetric.lower(metric),$0
    )
})
}
    
open func collections()throws  -> [String] {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_agentvec_collections(self.uniffiClonePointer(),$0
    )
})
}
    
open func dropCollection(name: String)throws  {try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_agentvec_drop_collection(self.uniffiClonePointer(),
        FfiConverterString.lower(name),$0
    )
}
}
    
open func getCollection(name: String)throws  -> Collection {
    return try  FfiConverterTypeCollection.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_agentvec_get_collection(self.uniffiClonePointer(),
        FfiConverterString.lower(name),$0
    )
})
}
    
open func recoveryStats() -> RecoveryStats {
    return try!  FfiConverterTypeRecoveryStats.lift(try! rustCall() {
    uniffi_agentvec_mobile_fn_method_agentvec_recovery_stats(self.uniffiClonePointer(),$0
    )
})
}
    
open func sync()throws  {try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_agentvec_sync(self.uniffiClonePointer(),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAgentVec: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = AgentVec

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> AgentVec {
        return AgentVec(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: AgentVec) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AgentVec {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: AgentVec, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgentVec_lift(_ pointer: UnsafeMutableRawPointer) throws -> AgentVec {
    return try FfiConverterTypeAgentVec.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgentVec_lower(_ value: AgentVec) -> UnsafeMutableRawPointer {
    return FfiConverterTypeAgentVec.lower(value)
}




public protocol CollectionProtocol : AnyObject {
    
    func add(vector: [Float], metadataJson: String, id: String?, ttl: UInt64?) throws  -> String
    
    func compact() throws  -> CompactStats
    
    func delete(id: String) throws  -> Bool
    
    func dimensions()  -> UInt32
    
    func exportToFile(path: String) throws  -> UInt64
    
    func get(id: String) throws  -> SearchResult?
    
    func getWithVector(id: String) throws  -> VectorRecord?
    
    func importFromFile(path: String) throws  -> ImportStats
    
    func isEmpty() throws  -> Bool
    
    func len() throws  -> UInt64
    
    func metric()  -> Metric
    
    func name()  -> String
    
    func preload() throws 
    
    func search(vector: [Float], k: UInt32, whereJson: String?) throws  -> [SearchResult]
    
    func sync() throws 
    
    func upsert(id: String, vector: [Float], metadataJson: String, ttl: UInt64?) throws 
    
    func vectorsSizeBytes()  -> UInt64
    
}

open class Collection:
    CollectionProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_agentvec_mobile_fn_clone_collection(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_agentvec_mobile_fn_free_collection(pointer, $0) }
    }

    

    
open func add(vector: [Float], metadataJson: String, id: String?, ttl: UInt64?)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_add(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(vector),
        FfiConverterString.lower(metadataJson),
        FfiConverterOptionString.lower(id),
        FfiConverterOptionUInt64.lower(ttl),$0
    )
})
}
    
open func compact()throws  -> CompactStats {
    return try  FfiConverterTypeCompactStats.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_compact(self.uniffiClonePointer(),$0
    )
})
}
    
open func delete(id: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_delete(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
open func dimensions() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_agentvec_mobile_fn_method_collection_dimensions(self.uniffiClonePointer(),$0
    )
})
}
    
open func exportToFile(path: String)throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_export_to_file(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
})
}
    
open func get(id: String)throws  -> SearchResult? {
    return try  FfiConverterOptionTypeSearchResult.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_get(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
open func getWithVector(id: String)throws  -> VectorRecord? {
    return try  FfiConverterOptionTypeVectorRecord.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_get_with_vector(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
open func importFromFile(path: String)throws  -> ImportStats {
    return try  FfiConverterTypeImportStats.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_import_from_file(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
})
}
    
open func isEmpty()throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_is_empty(self.uniffiClonePointer(),$0
    )
})
}
    
open func len()throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_len(self.uniffiClonePointer(),$0
    )
})
}
    
open func metric() -> Metric {
    return try!  FfiConverterTypeMetric.lift(try! rustCall() {
    uniffi_agentvec_mobile_fn_method_collection_metric(self.uniffiClonePointer(),$0
    )
})
}
    
open func name() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_agentvec_mobile_fn_method_collection_name(self.uniffiClonePointer(),$0
    )
})
}
    
open func preload()throws  {try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_preload(self.uniffiClonePointer(),$0
    )
}
}
    
open func search(vector: [Float], k: UInt32, whereJson: String?)throws  -> [SearchResult] {
    return try  FfiConverterSequenceTypeSearchResult.lift(try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_search(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(vector),
        FfiConverterUInt32.lower(k),
        FfiConverterOptionString.lower(whereJson),$0
    )
})
}
    
open func sync()throws  {try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_sync(self.uniffiClonePointer(),$0
    )
}
}
    
open func upsert(id: String, vector: [Float], metadataJson: String, ttl: UInt64?)throws  {try rustCallWithError(FfiConverterTypeAgentVecError.lift) {
    uniffi_agentvec_mobile_fn_method_collection_upsert(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterSequenceFloat.lower(vector),
        FfiConverterString.lower(metadataJson),
        FfiConverterOptionUInt64.lower(ttl),$0
    )
}
}
    
open func vectorsSizeBytes() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_agentvec_mobile_fn_method_collection_vectors_size_bytes(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCollection: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Collection

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Collection {
        return Collection(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Collection) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Collection {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Collection, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCollection_lift(_ pointer: UnsafeMutableRawPointer) throws -> Collection {
    return try FfiConverterTypeCollection.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCollection_lower(_ value: Collection) -> UnsafeMutableRawPointer {
    return FfiConverterTypeCollection.lower(value)
}


public struct CompactStats {
    public var expiredRemoved: UInt64
    public var tombstonesRemoved: UInt64
    public var bytesFreed: UInt64
    public var durationMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(expiredRemoved: UInt64, tombstonesRemoved: UInt64, bytesFreed: UInt64, durationMs: UInt64) {
        self.expiredRemoved = expiredRemoved
        self.tombstonesRemoved = tombstonesRemoved
        self.bytesFreed = bytesFreed
        self.durationMs = durationMs
    }
}



extension CompactStats: Equatable, Hashable {
    public static func ==(lhs: CompactStats, rhs: CompactStats) -> Bool {
        if lhs.expiredRemoved != rhs.expiredRemoved {
            return false
        }
        if lhs.tombstonesRemoved != rhs.tombstonesRemoved {
            return false
        }
        if lhs.bytesFreed != rhs.bytesFreed {
            return false
        }
        if lhs.durationMs != rhs.durationMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(expiredRemoved)
        hasher.combine(tombstonesRemoved)
        hasher.combine(bytesFreed)
        hasher.combine(durationMs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompactStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompactStats {
        return
            try CompactStats(
                expiredRemoved: FfiConverterUInt64.read(from: &buf), 
                tombstonesRemoved: FfiConverterUInt64.read(from: &buf), 
                bytesFreed: FfiConverterUInt64.read(from: &buf), 
                durationMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: CompactStats, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.expiredRemoved, into: &buf)
        FfiConverterUInt64.write(value.tombstonesRemoved, into: &buf)
        FfiConverterUInt64.write(value.bytesFreed, into: &buf)
        FfiConverterUInt64.write(value.durationMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompactStats_lift(_ buf: RustBuffer) throws -> CompactStats {
    return try FfiConverterTypeCompactStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompactStats_lower(_ value: CompactStats) -> RustBuffer {
    return FfiConverterTypeCompactStats.lower(value)
}


public struct ImportStats {
    public var imported: UInt64
    public var skipped: UInt64
    public var failed: UInt64
    public var durationMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(imported: UInt64, skipped: UInt64, failed: UInt64, durationMs: UInt64) {
        self.imported = imported
        self.skipped = skipped
        self.failed = failed
        self.durationMs = durationMs
    }
}



extension ImportStats: Equatable, Hashable {
    public static func ==(lhs: ImportStats, rhs: ImportStats) -> Bool {
        if lhs.imported != rhs.imported {
            return false
        }
        if lhs.skipped != rhs.skipped {
            return false
        }
        if lhs.failed != rhs.failed {
            return false
        }
        if lhs.durationMs != rhs.durationMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(imported)
        hasher.combine(skipped)
        hasher.combine(failed)
        hasher.combine(durationMs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImportStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImportStats {
        return
            try ImportStats(
                imported: FfiConverterUInt64.read(from: &buf), 
                skipped: FfiConverterUInt64.read(from: &buf), 
                failed: FfiConverterUInt64.read(from: &buf), 
                durationMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: ImportStats, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.imported, into: &buf)
        FfiConverterUInt64.write(value.skipped, into: &buf)
        FfiConverterUInt64.write(value.failed, into: &buf)
        FfiConverterUInt64.write(value.durationMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImportStats_lift(_ buf: RustBuffer) throws -> ImportStats {
    return try FfiConverterTypeImportStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImportStats_lower(_ value: ImportStats) -> RustBuffer {
    return FfiConverterTypeImportStats.lower(value)
}


public struct RecoveryStats {
    public var promoted: UInt64
    public var rolledBack: UInt64
    public var tombstones: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(promoted: UInt64, rolledBack: UInt64, tombstones: UInt64) {
        self.promoted = promoted
        self.rolledBack = rolledBack
        self.tombstones = tombstones
    }
}



extension RecoveryStats: Equatable, Hashable {
    public static func ==(lhs: RecoveryStats, rhs: RecoveryStats) -> Bool {
        if lhs.promoted != rhs.promoted {
            return false
        }
        if lhs.rolledBack != rhs.rolledBack {
            return false
        }
        if lhs.tombstones != rhs.tombstones {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(promoted)
        hasher.combine(rolledBack)
        hasher.combine(tombstones)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecoveryStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecoveryStats {
        return
            try RecoveryStats(
                promoted: FfiConverterUInt64.read(from: &buf), 
                rolledBack: FfiConverterUInt64.read(from: &buf), 
                tombstones: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: RecoveryStats, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.promoted, into: &buf)
        FfiConverterUInt64.write(value.rolledBack, into: &buf)
        FfiConverterUInt64.write(value.tombstones, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecoveryStats_lift(_ buf: RustBuffer) throws -> RecoveryStats {
    return try FfiConverterTypeRecoveryStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecoveryStats_lower(_ value: RecoveryStats) -> RustBuffer {
    return FfiConverterTypeRecoveryStats.lower(value)
}


public struct SearchResult {
    public var id: String
    public var score: Float
    public var metadataJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, score: Float, metadataJson: String) {
        self.id = id
        self.score = score
        self.metadataJson = metadataJson
    }
}



extension SearchResult: Equatable, Hashable {
    public static func ==(lhs: SearchResult, rhs: SearchResult) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.score != rhs.score {
            return false
        }
        if lhs.metadataJson != rhs.metadataJson {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(score)
        hasher.combine(metadataJson)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchResult {
        return
            try SearchResult(
                id: FfiConverterString.read(from: &buf), 
                score: FfiConverterFloat.read(from: &buf), 
                metadataJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SearchResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterFloat.write(value.score, into: &buf)
        FfiConverterString.write(value.metadataJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lift(_ buf: RustBuffer) throws -> SearchResult {
    return try FfiConverterTypeSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lower(_ value: SearchResult) -> RustBuffer {
    return FfiConverterTypeSearchResult.lower(value)
}


public struct VectorRecord {
    public var id: String
    public var vector: [Float]
    public var metadataJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, vector: [Float], metadataJson: String) {
        self.id = id
        self.vector = vector
        self.metadataJson = metadataJson
    }
}



extension VectorRecord: Equatable, Hashable {
    public static func ==(lhs: VectorRecord, rhs: VectorRecord) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.vector != rhs.vector {
            return false
        }
        if lhs.metadataJson != rhs.metadataJson {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(vector)
        hasher.combine(metadataJson)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVectorRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VectorRecord {
        return
            try VectorRecord(
                id: FfiConverterString.read(from: &buf), 
                vector: FfiConverterSequenceFloat.read(from: &buf), 
                metadataJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: VectorRecord, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterSequenceFloat.write(value.vector, into: &buf)
        FfiConverterString.write(value.metadataJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVectorRecord_lift(_ buf: RustBuffer) throws -> VectorRecord {
    return try FfiConverterTypeVectorRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVectorRecord_lower(_ value: VectorRecord) -> RustBuffer {
    return FfiConverterTypeVectorRecord.lower(value)
}


public enum AgentVecError {

    
    
    case IoError(message: String)
    
    case DatabaseError(message: String)
    
    case DimensionMismatch(message: String)
    
    case InvalidInput(message: String)
    
    case NotFound(message: String)
    
    case CollectionNotFound(message: String)
    
    case Serialization(message: String)
    
    case Other(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAgentVecError: FfiConverterRustBuffer {
    typealias SwiftType = AgentVecError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AgentVecError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .IoError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .DatabaseError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .DimensionMismatch(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .NotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .CollectionNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .Serialization(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .Other(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AgentVecError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .IoError(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .DatabaseError(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .DimensionMismatch(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .InvalidInput(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .NotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .CollectionNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .Serialization(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .Other(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))

        
        }
    }
}


extension AgentVecError: Equatable, Hashable {}

extension AgentVecError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Metric {
    
    case cosine
    case dot
    case l2
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMetric: FfiConverterRustBuffer {
    typealias SwiftType = Metric

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Metric {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .cosine
        
        case 2: return .dot
        
        case 3: return .l2
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Metric, into buf: inout [UInt8]) {
        switch value {
        
        
        case .cosine:
            writeInt(&buf, Int32(1))
        
        
        case .dot:
            writeInt(&buf, Int32(2))
        
        
        case .l2:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMetric_lift(_ buf: RustBuffer) throws -> Metric {
    return try FfiConverterTypeMetric.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMetric_lower(_ value: Metric) -> RustBuffer {
    return FfiConverterTypeMetric.lower(value)
}



extension Metric: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSearchResult: FfiConverterRustBuffer {
    typealias SwiftType = SearchResult?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSearchResult.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSearchResult.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeVectorRecord: FfiConverterRustBuffer {
    typealias SwiftType = VectorRecord?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeVectorRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeVectorRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [SearchResult]

    public static func write(_ value: [SearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchResult.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_agentvec_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_agentvec_collection() != 45186) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_agentvec_collections() != 20065) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_agentvec_drop_collection() != 15591) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_agentvec_get_collection() != 13291) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_agentvec_recovery_stats() != 10637) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_agentvec_sync() != 48480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_add() != 20557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_compact() != 55100) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_delete() != 53606) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_dimensions() != 5017) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_export_to_file() != 20337) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_get() != 52592) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_get_with_vector() != 64830) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_import_from_file() != 38779) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_is_empty() != 11836) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_len() != 53088) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_metric() != 8616) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_name() != 62077) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_preload() != 20111) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_search() != 45316) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_sync() != 63004) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_upsert() != 57719) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_method_collection_vectors_size_bytes() != 43005) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_agentvec_mobile_checksum_constructor_agentvec_open() != 16571) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all